USE [master]
GO

/****** Object:  Database [WebProgramming2021]    Script Date: 1/31/2021 10:48:59 PM ******/
CREATE DATABASE [WebProgramming2021]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WebProgramming2021', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\WebProgramming2021.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'WebProgramming2021_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\WebProgramming2021_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WebProgramming2021].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WebProgramming2021] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WebProgramming2021] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WebProgramming2021] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WebProgramming2021] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WebProgramming2021] SET ARITHABORT OFF 
GO

ALTER DATABASE [WebProgramming2021] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [WebProgramming2021] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WebProgramming2021] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WebProgramming2021] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WebProgramming2021] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WebProgramming2021] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WebProgramming2021] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WebProgramming2021] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WebProgramming2021] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WebProgramming2021] SET  ENABLE_BROKER 
GO

ALTER DATABASE [WebProgramming2021] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WebProgramming2021] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WebProgramming2021] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WebProgramming2021] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WebProgramming2021] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WebProgramming2021] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [WebProgramming2021] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WebProgramming2021] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [WebProgramming2021] SET  MULTI_USER 
GO

ALTER DATABASE [WebProgramming2021] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WebProgramming2021] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WebProgramming2021] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WebProgramming2021] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [WebProgramming2021] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WebProgramming2021] SET QUERY_STORE = OFF
GO

ALTER DATABASE [WebProgramming2021] SET  READ_WRITE 
GO

